### PR TITLE
Add vendoring

### LINKED ISSUE #9: [Vendoring] Add vendoring

### PR DESCRIPTION
**Pull request by 0xch4z**
Use [Go 1.11 Modules](https://github.com/golang/go/wiki/Modules) for vendoring.

Closes #9.

### CODE REVIEW

**Comment by iwittkau** [comment]
Hey @Charliekenney23, thanks for the PR! Since go modules are currently in an experimental phase, I am not sure I want to use them for vendoring. I created this issue as a reminder and a place for discussions on vendoring topics.

**Comment by iwittkau** [comment]
Maybe we can reopen this now, since Go Modules seem be here to stay 😄 .

**Comment by 0xch4z** [comment]
Awesome, so is this PR good to go?

**Comment by iwittkau** [comment]
@Charliekenney23 yes, thank you! I wanted to commit some stuff I was working on first.

**Pull request merged**
